name: Build and Test

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: '12'
          distribution: 'adopt'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: stable

      - name: Run Flutter Format
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: '12'
          distribution: 'adopt'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: stable

      - name: Run Flutter Analyze
        run: |
          flutter pub get
          flutter analyze

  test:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: '12'
          distribution: 'adopt'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: stable

      - name: Run Flutter Tests
        run: |
          flutter pub get
          flutter test

  build-apk:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: '12'
          distribution: 'adopt'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: stable

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --debug
